# Generated by Django 3.1.1 on 2020-09-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200927_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Listing1',
        ),
    ]
