# Generated by Django 3.1.1 on 2020-09-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200927_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing1',
            new_name='Listing',
        ),
    ]
