# Generated by Django 3.1.1 on 2020-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200927_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FASHION', 'Fashion'), ('ELECTRONICS', 'Electronics'), ('SPORTS', 'Sports'), ('HOBBIES', 'Hobbies'), ('HOME', 'Home'), ('MOTORS', 'Motors'), ('ART', 'Art'), ('BUSINESS', 'Business'), ('HEALTH', 'Health'), ('BEAUTY', 'Beauty'), ('MEDIA', 'Media'), ('OTHER', 'Other')], max_length=12),
        ),
    ]
